export const USER_SIGN_UP= "USER_SIGN_UP";




export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";


export const USER_LOG_IN_REQUEST = "USER_LOG_IN_REQUEST";
export const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export const USER_LOG_IN_FAIL = "USER_LOG_IN_FAIL";

export const USER_LOG_OUT = "USER_LOG_OUT";


export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const ADD_NEW_MOVIE_REQUEST = "ADD_NEW_MOVIE_REQUEST";
export const ADD_NEW_MOVIE_SUCCESS = "ADD_NEW_MOVIE_SUCCESS";
export const ADD_NEW_MOVIE_FAIL = "ADD_NEW_MOVIE_FAIL";

